/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.view;
import br.com.ifba.curso.dao.CursoDAO;
import br.com.ifba.curso.entity.Curso;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane; 
/**
 *
 * @author guilh
 */
public class CursoListar extends javax.swing.JFrame {
    
    private List<Curso> listaDeCursos = new ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoListar.class.getName());

    /**
     * Creates new form CursoListar
     */
    public CursoListar() {
        initComponents();
        preencherTabela(null);
    }
    
    /**
     * Busca os dados no DAO e preenche a JTable.
     */
    private void preencherTabela(String nomeBusca) {
        //Pega o "modelo" da sua tabela
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        //Limpa a tabela
        model.setRowCount(0); 

        //Buscar os dados no DAO
        CursoDAO cursoDAO = new CursoDAO();
        
        try { 
            //LÓGICA DA BUSCA:
            if (nomeBusca == null || nomeBusca.trim().isEmpty()) {
                // Se a busca for vazia, lista TODOS
                this.listaDeCursos = cursoDAO.listarTodos();
            } else {
                // Senão, lista os cursos FILTRADOS pelo nome
                this.listaDeCursos = cursoDAO.buscarPorNome(nomeBusca);
            }

            //Preenche a tabela com os dados da lista
            for (Curso curso : this.listaDeCursos) {
                model.addRow(new Object[]{
                    curso.getNome(),
                    curso.getCodigo()
                });
            }
            
        } catch (Exception e) { 
            //Tratamento de Exceção
            JOptionPane.showMessageDialog(this, 
                    "Erro ao carregar dados da tabela:\n" + e.getMessage(), 
                    "Erro", 
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "ID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 87, 508, 346));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, 50));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 58, 260, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
     
        CursoAdicionar telaAdicionar = new CursoAdicionar(this, true);
    
        telaAdicionar.setVisible(true);
    
        preencherTabela(null);
    
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    // 1Pega a linha selecionada na tabela
        int linhaSelecionada = jTable1.getSelectedRow();

        //Verifica se alguma linha foi realmente selecionada
        if (linhaSelecionada == -1) { // -1 significa nenhuma linha selecionada
            JOptionPane.showMessageDialog(this,
                    "Por favor, selecione um curso na tabela para editar.",
                    "Nenhum curso selecionado",
                    JOptionPane.WARNING_MESSAGE);
            return; // Para a execução do método
        }

        // Pega o objeto Curso da nossa lista interna
        //    (Baseado na linha que o usuário clicou)
        Curso cursoSelecionado = this.listaDeCursos.get(linhaSelecionada);

        //Cria a tela de Edição, passando o curso para ela
        CursoEditar telaEditar = new CursoEditar(this, true, cursoSelecionado);
        
        //Deixa a tela de Edição visível
        //O código vai "pausar" aqui até a telaEditar fechar
        telaEditar.setVisible(true);
        
        //atualiza a tabela!
        preencherTabela(null);
    }
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       //Pega a linha selecionada
        int linhaSelecionada = jTable1.getSelectedRow();

        //Verifica se selecionou
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, selecione um curso na tabela para excluir.",
                    "Nenhum curso selecionado",
                    JOptionPane.WARNING_MESSAGE);
            return; 
        }

        //Pega o objeto Curso da lista
        Curso cursoSelecionado = this.listaDeCursos.get(linhaSelecionada);

        int confirmacao = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja excluir o curso: \n" 
                    + cursoSelecionado.getNome() + "?",
                "Confirmação de Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        //Se o usuário disse "Sim"
        if (confirmacao == JOptionPane.YES_OPTION) {
            
            CursoDAO cursoDAO = new CursoDAO();
            
            try {
                //TENTA remover pelo ID
                cursoDAO.excluir(cursoSelecionado);
                
                // Mostra sucesso E atualiza a tabela
                JOptionPane.showMessageDialog(this, 
                        "Curso removido com sucesso!", 
                        "Sucesso", 
                        JOptionPane.INFORMATION_MESSAGE);
                
                preencherTabela(null);

            } catch (Exception e) {
                // Se a LINHA 6 falhou:
                // Mostra o erro e NÃO FAZ NADA na tabela.
                JOptionPane.showMessageDialog(this,
                        "Erro ao excluir o curso:\n" + e.getMessage(),
                        "Erro no Banco de Dados",
                        JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       //Pega a linha selecionada na tabela
        int linhaSelecionada = jTable1.getSelectedRow();

        //Verifica se alguma linha foi realmente selecionada
        if (linhaSelecionada == -1) { // -1 significa nenhuma linha selecionada
            JOptionPane.showMessageDialog(this,
                    "Por favor, selecione um curso na tabela para editar.",
                    "Nenhum curso selecionado",
                    JOptionPane.WARNING_MESSAGE);
            return; // Para a execução do método
        }

        //Pega o objeto Curso da nossa lista interna
        //    (Baseado na linha que o usuário clicou)
        Curso cursoSelecionado = this.listaDeCursos.get(linhaSelecionada);

        //Cria a tela de Edição, passando o curso para ela
        CursoEditar telaEditar = new CursoEditar(this, true, cursoSelecionado); // <-- ESTA É A LINHA CORRETA
        
        //Deixa a tela de Edição visível
        telaEditar.setVisible(true);
        
        preencherTabela(null);                                         
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        preencherTabela(jTextField1.getText());
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
