/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.view;
import java.awt.Frame; 
import br.com.ifba.curso.entity.Curso;
import br.com.ifba.curso.dao.CursoDAO; 
import jakarta.persistence.PersistenceException; 
import javax.swing.JOptionPane; 
/**
 *
 * @author guilh
 */
public class CursoEditar extends javax.swing.JDialog {
    
    private Curso cursoParaEditar;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoEditar.class.getName());

    /**
     * Creates new form CursoEditar
     */
    /**
 * Cria o formulário CursoEditar e já recebe o curso
 * que o usuário selecionou na outra tela.
 */
public CursoEditar(java.awt.Frame parent, boolean modal, Curso cursoParaEditar) {
    super(parent, modal); // Linha padrão do JDialog
    initComponents();

    //Salva o curso recebido na nossa variável de classe
    this.cursoParaEditar = cursoParaEditar;

    //Chama um método para preencher os campos
    preencherCampos();

    //Centraliza a tela
    setLocationRelativeTo(parent);
}

/**
     * Pega os dados do 'cursoParaEditar' e joga nos campos de texto.
     */
    private void preencherCampos() {
        
        // jTextField1 é o campo para o NOME
        // jTextField2 é o campo para o CÓDIGO
        jTextField1.setText(this.cursoParaEditar.getNome());
        jTextField2.setText(this.cursoParaEditar.getCodigo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setText("EDITAR CURSO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Insira o novo nome:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setText("Insira o novo codigo:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 156, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    //Pegar os NOVOS dados dos campos de texto
    //(Lembrando que jTextField1=Nome, jTextField2=Codigo)
    String novoNome = jTextField1.getText();
    String novoCodigo = jTextField2.getText();

    //Validação simples (Tratamento de Exceção)
    if (novoNome.isEmpty() || novoCodigo.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Por favor, preencha todos os campos!",
                "Erro de Validação",
                JOptionPane.ERROR_MESSAGE);
        return; // Para a execução
    }

    //ATUALIZA o objeto 'cursoParaEditar'
    //    (Este é o objeto que recebemos no construtor.
    //    Ele AINDA TEM O ID ORIGINAL!)
    this.cursoParaEditar.setNome(novoNome);
    this.cursoParaEditar.setCodigo(novoCodigo);

    // 4. Salvar no banco (usando o DAO)
    CursoDAO cursoDAO = new CursoDAO();

    try {
        //CHAMA O MÉTODO SALVAR()
        //    Como 'cursoParaEditar' TEM um ID, o JPA
        //    vai fazer um UPDATE, não um INSERT. É a mágica do 'merge'!
        cursoDAO.salvar(this.cursoParaEditar);

        //Se chegou aqui, deu certo
        JOptionPane.showMessageDialog(this,
                "Curso atualizado com sucesso!",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);

        //FECHA a tela de Edição
        this.dispose();

    } catch (PersistenceException e) {
        //Tratamento de Exceção (ex: código duplicado)
        JOptionPane.showMessageDialog(this,
                "Erro ao atualizar o curso:\n" + e.getMessage(),
                "Erro no Banco de Dados",
                JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
